name: isolate_contactor
description: An easy way to create a new Isolate, keep it active and communicate with it (supports `Worker` on the Web platform).
version: 3.0.0
homepage: https://github.com/vnniz/isolate_contactor

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  stream_channel: ^2.1.0

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.1
  js: ^0.6.5
